name: build-and-push-image

on:
  push:
    branches:
      - main

# Allow one concurrent deployment
concurrency:
  group: "build-and-push-image"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: pip install mkdocs-material
      - run: mkdocs build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: ghcr.io/${{ github.repository }}:0.0.1
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
